config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :participants, only: %i[index create update destroy]
    get '/sign_in_sheet.pdf', to: 'participants#sign_in_sheet', as: 'sign_in_sheet'
  end

  resources :announcements, except: [:index]

  root to: 'pages#root'
  get '/user/overview', to: 'pages#overview'

  namespace :admin do
    get '/dashboard', to: 'settings#dashboard', as: 'dashboard'
    get '/users', to: 'settings#users', as: 'users'
    patch '/modify_user/:id', to: 'settings#modify_user', as: 'modify_user'

    get '/settings', to: 'settings#settings', as: 'settings'
    patch '/update_settings', to: 'settings#update_settings', as: 'update_settings'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id'

  has_many :participants

  validates :title, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :participant_slots, presence: true
  validates :participant_slots, numericality: { only_integer: true, greater_than: 0 }

  validate :end_must_be_after_start

  scope :finished_events, -> { where('end_time < ?', DateTime.now) }
  scope :unfinished_events, -> { where('end_time > ?', DateTime.now) }

  def full?
    participant_slots <= participants.count
  end

  def finished?
    DateTime.now > end_time
  end

  def unfinished?
    !finished?
  end

  def total_hours
    ((end_time - start_time) / 3600).to_f
  end

  private

  def end_must_be_after_start
    errors.add(:end_time, 'must be after start time') if DateTime.new(start_time.to_i) > DateTime.new(end_time.to_i)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource

  def index
    @events = params[:finished].present? ? Event.finished_events : Event.unfinished_events
    respond_with @events
  end

  def show
    respond_with @event
  end

  def new
    respond_with @event
  end

  def edit
    respond_with @event
  end

  def create
    if @event.save
      head :created, location: event_path(@event)
    else
      render json: { error: @event.errors }, status: :bad_request
    end
  end

  def update
    if @event.update(update_params)
      head :ok
    else
      render json: { error: @event.errors }, status: :bad_request
    end
  end

  def destroy
    @event.destroy
    head :ok
  end

  private

  def create_params
    params.require(:event).permit(:title, :description, :start_time, :end_time, :location, :participant_slots, :manager_id)
  end

  def update_params
    params.require(:event).permit(:title, :description, :start_time, :end_time, :location, :participant_slots, :manager_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def user_select_list
    User.order(rank: :desc, first_name: :desc).map { |u| [u.full_name + ' - ' + u.rank_name, u.id] }
  end

  def format_datetime(datetime)
    datetime.strftime('%A, %b %e, %Y %l:%M%P')
  end

  def current_user_in_event(event)
    event.participants.find_by(user_id: current_user.id)
  end

  def get_slots_remaining(event)
    event.participant_slots - event.participants.count
  end
end

app/views/events/_event.html.erb
<tr>
  <td><%= event.title %></td>
  <td><%= get_slots_remaining event %></td>
  <td><%= get_date_string event.start_time %></td>
  <td><%= get_time_range event.start_time, event.end_time %></td>
  <td><%= event.location %></td>
  <td><%= link_to 'View', event_path(event), class: 'btn btn-sm btn-primary' %>
</tr>

app/views/events/_participant.html.erb
<li><%= participant.user.full_name %></li>

app/views/events/edit.html.erb
<div class="container">
  <h1>Edit Event</h1>
  <%= form_for @event, remote: true do |f| %>
    <fieldset class="form-group">
      <%= f.label :title, class: 'form-control-label' %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Event Title' %>
    </fieldset>
  
    <fieldset class="form-group">
      <%= f.label :description, class: 'form-control-label' %>
      <%= f.text_area :description, cols: 20, rows: 10, class: 'form-control', placeholder: 'Description' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :start_time, class: 'form-control-label' %>
      <%= f.datetime_local_field :start_time, class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :end_time, class: 'form-control-label' %>
      <%= f.datetime_local_field :end_time, class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :location, class: 'form-control-label' %>
      <%= f.text_field :location, class: 'form-control', placeholder: 'Event Address' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :participant_slots, class: 'form-control-label' %>
      <%= f.number_field :participant_slots, class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :manager, class: 'form-control-label' %>
      <%= f.select :manager_id, user_select_list, { include_blank: true }, { class: 'form-control' } %>
    </fieldset>
  
    <%= f.submit 'Update', class: 'btn btn-primary', data: { disable_with: 'Update' } %>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <h1><%= params[:finished] ? 'Past' : 'Current' %> Events</h1>
  <% if can? :manage, Event %>
    <%= link_to 'Create A New Event', new_event_path, class: 'btn btn-outline-primary btn-block' %>
  <% end %>
  <div style="overflow-x: auto;">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Event Name</th>
          <th>Slots Available</th>
          <th>Date</th>
          <th>Time</th>
          <th>Location</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'event', collection: @events, cached: true or '' %>
      </tbody>
    </table>
  </div>
  <%= link_to 'View Finished Event', events_path(finished: true), class: 'btn btn-secondary btn-block' unless params[:finished] %>
  <%= link_to 'View Current Event', events_path, class: 'btn btn-secondary btn-block' if params[:finished] %>
</div>

app/views/events/new.html.erb
<div class="container">
  <h1>New Event</h1>
  <%= form_for @event, remote: true do |f| %>
    <fieldset class="form-group">
      <%= f.label :title, class: 'form-control-label' %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Event Title' %>
    </fieldset>
  
    <fieldset class="form-group">
      <%= f.label :description, class: 'form-control-label' %>
      <%= f.text_area :description, cols: 20, rows: 10, class: 'form-control', placeholder: 'Description' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :start_time, class: 'form-control-label' %>
      <%= f.datetime_local_field :start_time, class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :end_time, class: 'form-control-label' %>
      <%= f.datetime_local_field :end_time, class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :location, class: 'form-control-label' %>
      <%= f.text_field :location, class: 'form-control', placeholder: 'Event Address' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :participant_slots, class: 'form-control-label' %>
      <%= f.number_field :participant_slots, class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :manager, class: 'form-control-label' %>
      <%= f.select :manager_id, user_select_list, { include_blank: true }, { class: 'form-control' } %>
    </fieldset>
  
    <%= f.submit 'Create', class: 'btn btn-primary', data: { disable_with: 'Create' } %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1>
    <%= @event.title %>
    <% if can? :sign_in_sheet, Event %>
      <div class="btn-group">
        <%= link_to 'View Sign In Sheet', event_sign_in_sheet_path(@event), class: 'btn btn-outline-primary' %>
        <% if can? :manage, Event %>
          <%= link_to 'Edit Event', edit_event_path(@event), class: 'btn btn-outline-primary' %>
        <% end %>
      </div>
    <% end %>
  </h1>
  <hr>
  <div class="row">
    <div class="col-md-8 col-sm-12">
      <p><%= simple_format @event.description %></p>
      <hr>
      <p>Location: <%= link_to @event.location, location_to_google_maps_search_link(@event.location) %></p>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Details</h5>
          <% if @event.manager.present? %>
            <p>Manager: <%= @event.manager.full_name %></p>
          <% else %>
            <p class="text-muted">This event current is not managed.</p>
          <% end %>
          <% if can? :create, Participant %>
            <% if @event.finished? %>
              <p class="text-success">This Event is Finished</p>
            <% elsif @event.full? %>
              <button type="button" class="btn btn-sm btn-primary btn-block" disabled>Event is Full</button>
            <% elsif !current_user_in_event(@event) %>
              <%= button_to 'Sign Up For Event', {event_id: @event.id, participant: {user_id: current_user.id}, controller: :participants, action: :create}, remote: true, method: :post, class: 'btn btn-primary btn-block btn-sm', id: 'join_event' %>
            <% else %>
              <%= button_to 'Leave Event', {event_id: @event.id, id: @event.participants.find_by(user_id: current_user.id).id, controller: :participants, action: :destroy}, remote: true, method: :delete, class: 'btn btn-danger btn-block btn-sm', id: 'leave_event' %>
            <% end %>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Start: <%= format_datetime @event.start_time %></li>
          <li class="list-group-item">End: <%= format_datetime @event.end_time %></li>
          <li class="list-group-item"><%= get_slots_remaining @event %> Remaining Slots</li>
          <% if can? :manage_participants, Event %>
            <li class="list-group-item"><%= link_to 'Manage Participants', event_participants_path(@event), class: 'btn btn-outline-primary btn-block' %></li>
          <% end %>
        </ul>
        <% if @event.participants.count > 0 %>
          <% if can? :view_list, Participant %>
            <div class="card-header" id="headingTwo">
              <h5 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#viewPart" aria-expanded="false" aria-controls="viewPart">
                  View Participants
                </button>
              </h5>
            </div>
            <div id="viewPart" class="collapse" aria-labelledby="headingTwo">
              <div class="card-body">
                <ul>
                  <%= render partial: 'participant', collection: @event.participants %>
                </ul>
              </div>
            </div>
          <% else %>
            <div class="card-header" id="headingTwo">
              Please <%= link_to "log in", new_user_session_path %> to view this event's participants.
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>