config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :participants, only: %i[index create update destroy]
    get '/sign_in_sheet.pdf', to: 'participants#sign_in_sheet', as: 'sign_in_sheet'
  end

  resources :announcements, except: [:index]

  root to: 'pages#root'
  get '/user/overview', to: 'pages#overview'

  namespace :admin do
    get '/dashboard', to: 'settings#dashboard', as: 'dashboard'
    get '/users', to: 'settings#users', as: 'users'
    patch '/modify_user/:id', to: 'settings#modify_user', as: 'modify_user'

    get '/settings', to: 'settings#settings', as: 'settings'
    patch '/update_settings', to: 'settings#update_settings', as: 'update_settings'
  end
end

app/views/pages/_announcement.html.erb
<div class="media">
  <div class="media-body">
    <h4><%= announcement.title %></h4>
    <b class="text-muted">posted by <%= announcement.user.full_name %></b>
    <p><%= simple_format truncate(announcement.description, length: 350) { link_to 'Continue', announcement_path(announcement) } %></p>
  </div>
</div>

app/views/pages/_dashboard.html.erb
<div class="container">
  <h1>Welcome <%= current_user.first_name %></h1>
  <div class="row">
    <div class="col-md-4 order-1 col-sm-12">
      <h5>Upcoming Events</h5>
      <hr>
      <%= render partial: 'upcoming_event', collection: upcoming_events(current_user) or 'No Upcoming Events.' %>
    </div>
    <div class="col-md-8 col-sm-12">
      <h5>Recent Announcements</h5>
      <hr>
      <%= render partial: 'announcement', collection: Announcement.last(5).reverse  or 'No Announcements Posted.' %>
    </div>
  </div>
</div>

app/views/pages/_participation.html.erb
<tr>
  <td><%= participation.event.title %></td>
  <td><%= get_date_string participation.event.start_time %></td>
  <td><%= participation.event.total_hours %></td>
  <td>
    <%= participation.hours_gained %>
    <% if participation.event.finished? %>
      <% if participation.hours_gained < participation.event.total_hours %>
        <i class="fa fa-exclamation-circle" data-toggle="tooltip" data-placement="right" title="The manager of the event has marked that you were not there the entire time. If you believe this is a mistake, please contact an officer or advisor."></i>
      <% end %>
    <% else %>
      <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="This event is still active. Your hours for this event will be applied once the event is finished."></i>
    <% end %>
  </td>
  <td><%= link_to 'View Event Page', event_path(participation.event), class: 'btn btn-sm btn-primary' %>
</tr>

app/views/pages/_upcoming_event.html.erb
<div class="card card-body">
  <h6 class="card-title">
    <%= upcoming_event.event.title %>
  </h6>
  <div class="card-subtitle mb-2 text-muted">
    <%= get_date_string(upcoming_event.event.start_time) + ' ' + get_time_range(upcoming_event.event.start_time, upcoming_event.event.end_time) %> 
  </div>
  Location: <%= link_to upcoming_event.event.location, location_to_google_maps_search_link(upcoming_event.event.location) %>
  <hr>
  <%= link_to 'More Information', event_path(upcoming_event.event), class: 'btn btn-primary btn-block btn-sm' %>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Welcome <%= current_user.first_name %></h1>
  <div class="row">
    <div class="col-md-4 order-1 col-sm-12">
      <h5>Your Overview</h5>
      <hr>
      <p class="lead">
        Total Hours: <%= current_user.total_hours %>
      </p>
      <%= link_to 'View Hour Overview', user_overview_path, class: 'btn btn-block btn-small btn-primary' %>
      <hr>
      <h5>Upcoming Events</h5>
      <hr>
      <%= render partial: 'upcoming_event', collection: upcoming_events(current_user) or 'No Upcoming Events.' %>
    </div>
    <div class="col-md-8 col-sm-12">
      <h5>Recent Announcements</h5>
      <hr>
      <%= render partial: 'announcement', collection: Announcement.last(5).reverse, cached: true  or 'No Announcements Posted.' %>
    </div>
  </div>
</div>

app/views/pages/overview.html.erb
<div class="container">
  <h2>Overview of <%= current_user.full_name %></h2>
  <div class="card-deck">
    <div class="card text-center">
      <div class="card-header">
        Total Event Participations
      </div>
      <div class="card-body">
        <h1 class="display-2"><%= @participations.count %></h1>
      </div>
    </div>
    <div class="card text-center">
      <div class="card-header">
        Total Possible Hour Gain
      </div>
      <div class="card-body">
        <h1 class="display-2"><%= @total_possible_hours %></h1>
      </div>
    </div>
    <div class="card text-center">
      <div class="card-header">
        Total Hours Gained
      </div>
      <div class="card-body">
        <h1 class="display-2"><%= current_user.total_hours %></h1>
      </div>
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Event Name</th>
        <th>Date</th>
        <th>Total Possible Hours</th>
        <th>Total Hours Gained</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'participation', collection: @participations, cached: true or '' %>
    </tbody>
  </table>
</div>