config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :participants, only: %i[index create update destroy]
    get '/sign_in_sheet.pdf', to: 'participants#sign_in_sheet', as: 'sign_in_sheet'
  end

  resources :announcements, except: [:index]

  root to: 'pages#root'
  get '/user/overview', to: 'pages#overview'

  namespace :admin do
    get '/dashboard', to: 'settings#dashboard', as: 'dashboard'
    get '/users', to: 'settings#users', as: 'users'
    patch '/modify_user/:id', to: 'settings#modify_user', as: 'modify_user'

    get '/settings', to: 'settings#settings', as: 'settings'
    patch '/update_settings', to: 'settings#update_settings', as: 'update_settings'
  end
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  source Rails.root.join('config/app.yml')

  # When config/app.yml has changed, you need change this prefix to v2, v3 ... to expires caches
  cache_prefix { 'v1' }
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  authorize_resource

  def dashboard
    render
  end

  def users
    @users = User.all.order('rank DESC')
    respond_with @users
  end

  def modify_user
    user = User.find_by(id: params[:id])
    if user.update_without_password(modify_user_params)
      head :ok
    else
      render json: { error: user.errors }, status: :bad_request
    end
  end

  def settings
    @settings = Setting.get_all
    respond_with @settings
  end

  def update_settings
    return head :bad_request if params[:club].nil? || params[:navbarStyle].nil? || params[:navbarColor].nil?
    ActiveRecord::Base.transaction do
      Setting['club'] = params[:club]
      Setting['navbarStyle'] = params[:navbarStyle]
      Setting['navbarColor'] = params[:navbarColor]
    end

    head :ok
  end

  private

  def modify_user_params
    params.require(:user).permit(:rank, :deactivated)
  end
end

app/views/admin/settings/_menu.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Dashboard", admin_dashboard_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to "Users", admin_users_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to "Site Settings", admin_settings_path, class: 'nav-link' %>
  </li>
</ul>

app/views/admin/settings/_user.html.erb
<tr>
  <td><%= user.full_name %></td>
  <td><%= user.email %></td>
  <td><%= user.phone_number %></td>
  <td><%= user.total_hours %></td>
  <td class='user_rank'>
    <%= form_for user, url: admin_modify_user_path(user), remote: true do |f| %>
      <fieldset class="form-group">
        <%= f.select :rank, User.ranks.keys.to_a, { selected: user.rank }, { class: 'form-control' } %>
      </fieldset>
    <% end %>
  </td>
  <td class='user_deactivated'>
    <%= form_for user, url: admin_modify_user_path(user), remote: true do |f| %>
      <fieldset class="form-group">
        <%= f.check_box :deactivated, { class: 'form-control' } %>
      </fieldset>
    <% end %>
  </td>
</tr>

app/views/admin/settings/dashboard.html.erb
<div class="container">
  <%= render 'menu' %>
  <h1>Dashboard</h1>
  <div class="card-deck">
    <div class="card text-center">
      <div class="card-header">
        Total Registered Users
      </div>
      <div class="card-body">
        <h1 class="display-2"><%= User.count %></h1>
      </div>
    </div>
    <div class="card text-center">
      <div class="card-header">
        Total Created Events
      </div>
      <div class="card-body">
        <h1 class="display-2"><%= Event.count %></h1>
      </div>
    </div>
    <div class="card text-center">
      <div class="card-header">
        Total Event Participants
      </div>
      <div class="card-body">
        <h1 class="display-2"><%= Participant.count %></h1>
      </div>
    </div>
  </div>
</div>


app/views/admin/settings/settings.html.erb
<div class="container">
  <%= render 'menu' %>
</div>
<div class="container">
  <h1>Edit Site Settings</h1>
  <%= form_tag admin_update_settings_path, remote: true, method: :patch do %>
    <fieldset class="form-group">
      <%= label_tag :club, 'Club Name', class: 'form-control-label' %>
      <%= text_field_tag :club, @settings["club"], class: 'form-control', placeholder: 'Club Name' %>
    </fieldset>

    <fieldset class="form-group">
      <%= label_tag :navbarStyle, 'Navigation Bar Style', class: 'form-control-label' %>
      <%= select_tag :navbarStyle, options_for_select(['light', 'dark'], @settings["navbarStyle"]), class: 'form-control' %>
    </fieldset>

    <fieldset class="form-group">
      <%= label_tag :navbarColor, 'Navigation Bar Style', class: 'form-control-label' %>
      <%= color_field_tag :navbarColor, @settings["navbarColor"], class: 'form-control' %>
    </fieldset>
  
    <%= submit_tag 'Update', class: 'btn btn-primary', data: { disable_with: 'Update' } %>
  <% end %>
</div>

app/views/admin/settings/show.html.erb

<div class="container">
  <%= render 'menu' %>
</div>


app/views/admin/settings/users.html.erb
<div class="container">
  <%= render 'menu' %>
</div>
<div class="container-fluid" style="overflow-x: auto;">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Full Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Total Hours</th>
        <th>Rank</th>
        <th>Deactivated?</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'user', collection: @users, cached: true %>
    </tbody>
  </table>
</div>